# Site settings
author: Eric An
title: DataSense
header-img: img/home-bg.png
email: eaerican@gmail.com
copyright_name: Eric An
description: > # this means to ignore newlines until "baseurl:"
  Journey into DataScience 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FIerican

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
